// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9rMUxVga_o8lQ5LusqKFDvItsjZN6Nc',
    appId: '1:557766983078:web:a7ce887f62aa503916a367',
    messagingSenderId: '557766983078',
    projectId: 'nilshobdo-87fce',
    authDomain: 'nilshobdo-87fce.firebaseapp.com',
    storageBucket: 'nilshobdo-87fce.firebasestorage.app',
    measurementId: 'G-DCB93X9YDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFarBnWhH-Er8Wv1nXaKt6MYhkPsB-Z-Y',
    appId: '1:557766983078:android:2f78751f49c1accf16a367',
    messagingSenderId: '557766983078',
    projectId: 'nilshobdo-87fce',
    storageBucket: 'nilshobdo-87fce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMu3wgvOzlBEYE-kTB-ZaQo4HdSTji_CI',
    appId: '1:557766983078:ios:1223fb7b6e8c95e216a367',
    messagingSenderId: '557766983078',
    projectId: 'nilshobdo-87fce',
    storageBucket: 'nilshobdo-87fce.firebasestorage.app',
    iosBundleId: 'com.example.nilshobdoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMu3wgvOzlBEYE-kTB-ZaQo4HdSTji_CI',
    appId: '1:557766983078:ios:1223fb7b6e8c95e216a367',
    messagingSenderId: '557766983078',
    projectId: 'nilshobdo-87fce',
    storageBucket: 'nilshobdo-87fce.firebasestorage.app',
    iosBundleId: 'com.example.nilshobdoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9rMUxVga_o8lQ5LusqKFDvItsjZN6Nc',
    appId: '1:557766983078:web:8c4095ce59265a3416a367',
    messagingSenderId: '557766983078',
    projectId: 'nilshobdo-87fce',
    authDomain: 'nilshobdo-87fce.firebaseapp.com',
    storageBucket: 'nilshobdo-87fce.firebasestorage.app',
    measurementId: 'G-1Y7RPS7JD0',
  );
}
